[buildpack]
id = "codedswitch-nodejs"
name = "CodedSwitch Node.js Buildpack"
version = "1.0.0"

[[buildpack.licenses]]
type = "MIT"
uri = "https://opensource.org/licenses/MIT"

[metadata]
include_files = ["bin/", "lib/"]
pre_package = "scripts/build.sh"

[[stacks]]
id = "heroku-22"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "io.buildpacks.stacks.jammy" 